---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  # Debian 12 - Bookworm
  - name: role-git_debian12_${MOLECULE_INSTANCE_ID}
    image: "python:3.11.4-bookworm"
    pre_build_image: true

  # Debian 11 - Bullseye
  - name: role-git_debian11_${MOLECULE_INSTANCE_ID}
    image: "python:3.11.4-bullseye"
    pre_build_image: true

  # Debian 10 - Buster
  - name: role-git_debian10_${MOLECULE_INSTANCE_ID}
    image: "python:3.11.4-buster"
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: testinfra
