---
- name: "Install mc"
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  loop: "{{ __mc_packages }}"
