galaxy_info:
  role_name: btop
  author: sjlex
  description: An Ansible role to install and configure btop.
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
      - bookworm
      - bullseye
      - buster

  galaxy_tags:
    - btop

dependencies: []
