---
- name: "Copy .gitconfig"
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: '{{ ansible_env["HOME"] }}/.gitconfig'
    mode: 0644

- name: "Copy .gitignore"
  ansible.builtin.copy:
    src: .gitignore
    dest: '{{ ansible_env["HOME"] }}/.gitignore'
    mode: 0644
