---
- name: "Converge"
  hosts: all
  remote_user: "ansible"

  tasks:
    - name: "Include docker"
      ansible.builtin.include_role:
        name: "docker"

    - name: "Add User to group"
      become: true
      become_user: root
      ansible.builtin.user:
        name: "ansible"
        groups: "docker"
        append: true
