galaxy_info:
  role_name: git
  author: sjlex
  description: An Ansible role to install and configure git.
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
      - bookworm
      - bullseye
      - buster

  galaxy_tags:
    - git

dependencies: []
