galaxy_info:
  role_name: bat
  author: sjlex
  description: An Ansible role to install and configure bat.
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
      - bookworm
      - bullseye
      - buster

  galaxy_tags:
    - bat

dependencies: []
